services:
#  myspot.api:
#    image: myspot.api
#    build:
#      context: .
#      dockerfile: src/MySpot.Api/Dockerfile
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      
  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    volumes:
      - seq:/data
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    
        
volumes:
  postgres_data:
    driver: local
  seq:
    driver: local
